Name:           ros-indigo-sr-visualization
Version:        1.3.1
Release:        0%{?dist}
Summary:        ROS sr_visualization package

Group:          Development/Libraries
License:        GPL
URL:            http://ros.org/wiki/sr_visualization
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-sr-gui-bootloader
Requires:       ros-indigo-sr-gui-change-controllers
Requires:       ros-indigo-sr-gui-change-muscle-controllers
Requires:       ros-indigo-sr-gui-controller-tuner
Requires:       ros-indigo-sr-gui-grasp-controller
Requires:       ros-indigo-sr-gui-hand-calibration
Requires:       ros-indigo-sr-gui-joint-slider
Requires:       ros-indigo-sr-gui-motor-resetter
Requires:       ros-indigo-sr-gui-movement-recorder
Requires:       ros-indigo-sr-gui-muscle-driver-bootloader
Requires:       ros-indigo-sr-gui-self-test
Requires:       ros-indigo-sr-visualization-icons
BuildRequires:  ros-indigo-catkin

%description
This stack contains the different gui plugins used with the shadow robot stacks.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 21 2014 Shadow Robot's software team <software@shadowrobot.com> - 1.3.1-0
- Autogenerated by Bloom

